services:
  
  gate-keeper:
    container_name: go-admin
    image: go-admin:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     CACHE_BUST: ${CACHE_BUST}
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      APPLICATION_PORT: ${APPLICATION_PORT}
    ports:
        - '8080:8080'
    expose:
     - '8080'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1;"]
      interval: 19s
      timeout: 5s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
    # volumes:
    #   - ./src:/app/src

  mysql:
   image: mysql:8.0.32
   command: --default-authentication-plugin=mysql_native_password --local-infile=ON
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     MYSQL_DATABASE: ${DB_NAME}
     MYSQL_USER: ${DB_USER}
     MYSQL_PASSWORD: ${DB_PASSWORD}
   ports:
     - '3306:3306'
   expose:
     - '3306'
   volumes:
     - 'go-admin-mysql-data:/var/lib/mysql'
   healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  apidoc:
    image: styled-swagger-ui:latest
    # image: swaggerapi/swagger-ui
    restart: always
    ports:
      - '8081:80'
    expose:
      - '8081'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./apidoc:/usr/share/nginx/html/apidoc
      # - ./config/config.json:/usr/share/nginx/html/config.json:ro

  redis:
    image: redis
    volumes:
      - go-admin-redis-data:/data
    ports:
      - '6379:6379'
    expose:
      - '6379'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  go-admin-mysql-data:
    driver: local
  go-admin-redis-data:
    driver: local