services:
  
  gate-keeper:
    container_name: gate_keeper
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHE_BUST: ${CACHE_BUST}
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      APPLICATION_PORT: ${APPLICATION_PORT}
    ports:
        - '8080:8080'
    expose:
     - '8080'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1;"]
      interval: 19s
      timeout: 5s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./src:/app/src

  mysql:
   image: mysql:8.0.32
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     MYSQL_DATABASE: ${DB_NAME}
     MYSQL_USER: ${DB_USER}
     MYSQL_PASSWORD: ${DB_PASSWORD}
   ports:
     - '3306:3306'
   expose:
     - '3306'
   volumes:
     - 'gate_keeper_mysql_data:/var/lib/mysql'
   healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  apidoc:
    image: swaggerapi/swagger-ui
    restart: always
    environment:
      SWAGGER_JSON: /api/spec.yaml
    ports:
        - '8081:8080'
    expose:
     - '8081'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./apidoc:/api

volumes:
  gate_keeper_mysql_data:
    driver: local