openapi: 3.0.0
info:
  title: Go Gate Keeper API
  version: 1.0.0
paths:
  /orgType:
    $ref: './paths/orgType.yaml#/paths/~1orgType'
  /orgType/{Id}:
    $ref: './paths/orgType.yaml#/paths/~1orgType~1{Id}'
  /subTier:
    $ref: './paths/subTier.yaml#/paths/~1subTier'
  /subTier/{Id}:
    $ref: './paths/subTier.yaml#/paths/~1subTier~1{Id}'
  /endpoint:
    $ref: './paths/endpoint.yaml#/paths/~1endpoint'
  /endpoint/{Id}:
    $ref: './paths/endpoint.yaml#/paths/~1endpoint~1{Id}'
  /org:
    $ref: './paths/organization.yaml#/paths/~1org'
  /org/{Id}:
    $ref: './paths/organization.yaml#/paths/~1org~1{Id}'
  /tierPricing:
    $ref: './paths/tierPricing.yaml#/paths/~1tierPricing'
  /tierPricing/{tier_id}:
    $ref: './paths/tierPricing.yaml#/paths/~1tierPricing~1{tier_id}'
  /tierPricing/{id}:
    $ref: './paths/tierPricing.yaml#/paths/~1tierPricing~1{id}'
  /subscription:
    $ref: './paths/subscription.yaml#/paths/~1subscription'
  /subscription/id/{id}:
    $ref: './paths/subscription.yaml#/paths/~1subscription~1id~1{id}'
  /subscription/orgId/{organization_id}:
    $ref: './paths/subscription.yaml#/paths/~1subscription~1orgId~1{organization_id}'
  /subscription/{id}:
    $ref: './paths/subscription.yaml#/paths/~1subscription~1{id}'
  /subscription/{organization_id}:
    $ref: './paths/subscription.yaml#/paths/~1subscription~1organization~1{organization_id}'
  /customPricing:
    $ref: './paths/customPricing.yaml#/paths/~1customPricing'
  /customPricing/{subscription_id}:
    $ref: './paths/customPricing.yaml#/paths/~1customPricing~1{subscription_id}'
  /customPricing/subId/{subscription_id}:
    $ref: './paths/customPricing.yaml#/paths/~1customPricing~1subId~1{subscription_id}'
  /customPricing/id/{id}:
    $ref: './paths/customPricing.yaml#/paths/~1customPricing~1id~1{id}'
  /resourceType:
    $ref: './paths/resourceType.yaml#/paths/~1resourceType'
  /resourceType/{id}:
    $ref: './paths/resourceType.yaml#/paths/~1resourceType~1{id}'
  /orgPermission:
    $ref: './paths/orgPermission.yaml#/paths/~1orgPermission'
  /orgPermission/{organization_id}:
    $ref: './paths/orgPermission.yaml#/paths/~1orgPermission~1{organization_id}'
